import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from 'react';
import { Navbar, Footer, LegalDisclaimer, FallbackLoader, HeroSection, DownloadSteps, ThemeProviderWrapper, ToastProvider } from "@/constants";

export const metadata: Metadata = {
  title: "Fast Save App",
  description: "Generated by Sanjay",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProviderWrapper>
          <Navbar />
          <Suspense fallback={<FallbackLoader />}>
            {children}
          </Suspense>
          <HeroSection />
          <DownloadSteps />
          <LegalDisclaimer />
          <Footer />
          <ToastProvider />
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}