import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from 'react';
import { Navbar, Footer, Loader, LegalDisclaimer, HeroSection, DownloadSteps, ThemeProviderWrapper, CategoryNav } from "@/constants";
import { ToastProvider } from "@/lib/toast-context";

export const metadata: Metadata = {
  title: "Fast Save App",
  description: "Generated by Sanjay",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProviderWrapper>
          <ToastProvider>
            <Navbar />
            <Suspense fallback={<Loader />}>
              {children}
            </Suspense>
            <HeroSection />
            <DownloadSteps />
            <LegalDisclaimer />
            <Footer />
          </ToastProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}