import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from 'react';
import dynamic from "next/dynamic";
import { Navbar, Footer, FallbackLoader, ThemeProviderWrapper, ToastProvider } from "@/constants";
const HeroSection = dynamic(() => import('@/components/sections/HeroSection'), { ssr: false });
const DownloadSteps = dynamic(() => import('@/components/sections/DownloadSteps'), { ssr: false });
const LegalDisclaimer = dynamic(() => import('@/components/sections/LegalDisclaimer'), { ssr: false });

export const metadata: Metadata = {
  title: "Fast Save",
  description: "Generated by Sanjay",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProviderWrapper>
          <Navbar />
          <Suspense fallback={<FallbackLoader />}>
            {children}
          </Suspense>
          <HeroSection />
          <DownloadSteps />
          <LegalDisclaimer />
          <Footer />
          <ToastProvider />
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}